""" version which can be consumed from within the module """
VERSION_STR = "0.0.18"
DESCRIPTION = "pyeventsummary is a way to aggregate and report on a host of errors and actions"
APP_NAME = "pyeventsummary"
LOGGER_NAME = "pyeventsummary"
